### ISSUE TITLE
Default generated code has lint errors

### ISSUE THREAD

**Issue by MetaMemoryT** [thaiat/generator-angular-famous-ionic#173]
The default generated code has these lint errors:

```
$ gulp lint
[16:42:15] Using gulpfile ~\p\App\gulpfile.js
[16:42:15] Starting 'static'...
[16:42:17] Error in plugin 'gulp-jscs'
Message:
    Operator === should not stick to following expression at tasks\browserify.js :
    35 |        .pipe(source(bundleName))
    36 |        .pipe(buffer())
    37 |        .pipe(gulpif(mode ==='prod', transform(function() {
-------------------------------------^
    38 |            return exorcist(path.join(constants.exorcist.dest, bundleName + '.' + version + '.map'), path.join(dest, bundleName + '.' + version + '.map'));
    39 |        })))
[16:42:17]
C:\Users\Sean\p\App\client\scripts\main.js
  8:58  error  Unexpected trailing comma  comma-dangle

C:\Users\Sean\p\App\gulp_tasks\tasks\browserify.js
  37:21  error  Infix operators must be spaced  space-infix-ops
  51:49  error  Unexpected trailing comma       comma-dangle

C:\Users\Sean\p\App\gulp_tasks\tasks\test.js
  33:20  warning  Don't use process.exit(); throw an error instead  no-process-exit

✖ 4 problems (3 errors, 1 warning)

[16:42:17] 'static' errored after 2.02 s
[16:42:17] ESLintError in plugin 'gulp-eslint'
Message:
    Unexpected trailing comma.
Details:
    fileName: C:\Users\Sean\p\App\client\scripts\main.js
    lineNumber: 8
[16:42:17] lint failed
C:\Users\Sean\p\App\gulp_tasks\tasks\lint.js:174
                throw new Error('lint_error');
                      ^
Error: lint_error
  at DestroyableTransform.<anonymous> (C:\Users\Sean\p\App\gulp_tasks\tasks\lint.js:174:23)
  at DestroyableTransform.emit (events.js:129:20)
  at C:\Users\Sean\p\App\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by thaiat** [comment]
@MetaMemoryT 
we just published a new version that should fix this issue
can you
```bash
npm install -g generator-sublime
npm install -g generator-angular-famous-ionic
```
and you u should be good to go

**Comment by thaiat** [comment]
closing that for the moment, feel free to reopen if the issue is still there

**Comment by MetaMemoryT** [comment]
this needs to be reopened as their is 2 errors that were not fixed:

```
C:\Users\Sean\p\App2\gulp_tasks\tasks\test.js
  33:20  warning  Don't use process.exit(); throw an error instead  no-process-exit
```

```
C:\Users\Sean\p\App2\gulp_tasks\tasks\lint.js:174
                throw new Error('lint_error');
                      ^
Error: lint_error
  at DestroyableTransform.<anonymous> (C:\Users\Sean\p\App2\gulp_tasks\tasks\lint.js:174:23)
  at DestroyableTransform.emit (events.js:129:20)
  at C:\Users\Sean\p\App2\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by thaiat** [comment]
can you paste the entire output of gulp lint 
i dont see the cause of the second error

**Comment by MetaMemoryT** [comment]
```
$ gulp lint
[15:36:06] Using gulpfile ~\p\GMedRoots\gulpfile.js
[15:36:06] Starting 'static'...
[15:36:08]
C:\Users\Sean\p\GMedRoots\client\scripts\main.js
  7:44  error  Unexpected trailing comma  comma-dangle

C:\Users\Sean\p\GMedRoots\client\scripts\data\services\dataService.js
  16:42  error  Unexpected token *

C:\Users\Sean\p\GMedRoots\gulp_tasks\tasks\test.js
  33:20  warning  Don't use process.exit(); throw an error instead  no-process-exit

✖ 3 problems (2 errors, 1 warning)

[15:36:08] lint failed
C:\Users\Sean\p\GMedRoots\gulp_tasks\tasks\lint.js:174
                throw new Error('lint_error');
                      ^
Error: lint_error
  at DestroyableTransform.<anonymous> (C:\Users\Sean\p\GMedRoots\gulp_tasks\tasks\lint.js:174:23)
  at DestroyableTransform.emit (events.js:129:20)
  at DestroyableTransform.gulp.src.pipe.plumber.errorHandler (C:\Users\Sean\p\GMedRoots\gulp_tasks\tasks\lint.js:158:26)
  at DestroyableTransform.emit (events.js:129:20)
  at onwriteError (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
  at onwrite (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
  at WritableState.onwrite (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
  at afterTransform (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
  at TransformState.afterTransform (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
  at DestroyableTransform._transform (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\index.js:75:10)
  at DestroyableTransform.Transform._read (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
  at doWrite (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
  at writeOrBuffer (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
  at write (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
  at flow (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:129:20)
  at emitReadable_ (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
  at emitReadable (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
  at readableAddChunk (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
  at DestroyableTransform.<anonymous> (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\src\reporters\fail.js:33:16)
  at Array.forEach (native)
  at DestroyableTransform.flush (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\src\reporters\fail.js:32:16)
  at DestroyableTransform._flush (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\src\stream.js:41:13)
  at DestroyableTransform.<anonymous> (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:199:16)
  at DestroyableTransform.emit (events.js:129:20)
  at finishMaybe (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
  at endWritable (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
  at DestroyableTransform.Writable.end (C:\Users\Sean\p\GMedRoots\node_modules\gulp-jshint\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
  at DestroyableTransform.onend (C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:199:16)
  at DestroyableTransform.emit (events.js:129:20)
  at C:\Users\Sean\p\GMedRoots\node_modules\gulp-eslint\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
  at process._tickDomainCallback (node.js:381:11)
```

**Comment by thaiat** [comment]
ok I see now
the warning is just a warning you can ignore it

as per the lint issue in main.js you have to fix it manually
the reason is that yeoman templating is adding extra spaces when multiple values are outputed 

another reason is that you have to create at least one module in your app before running lint as there is a trailing comma in the list of dependencies for the main module
